expose:
  Args: 
    - --v
    - 4
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded

cleanup:
  Args: 
    - --cleanup
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
expose:
  config:
    domain: 51.144.45.79.nip.io
    exposer: Ingress
    http: "true"
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
jenkins:
  Servers:
    Global:
      EnvVars:
        DOCKER_REGISTRY: minnowberyl.azurecr.io
        TILLER_NAMESPACE: kube-system
PipelineSecrets:
  DockerConfig: '{"auths":{"minnowberyl.azurecr.io":{"auth":"bWlubm93YmVyeWw6NkpxaERCOHZGdFByUlVuVHR5U1Q4ZTQweT1rPVYwWmg="}}}'
